export const DISPLAY_NAVBAR = 'DISPLAY_NAVBAR';
export const FETCH_ABOUT_MARKDOWN = 'FETCH_ABOUT_MARKDOWN';
export const FETCH_SKILLS = 'FETCH_SKILLS';
export const FETCH_SKILL = 'FETCH_SKILL';
export const SET_ACTIVE_SKILL = 'SET_ACTIVE_SKILL';
